---
jobs:
#### Staging Jobs
- name: generate-stage-site
  serial: true
  plan:
  - aggregate:
    - get: steeltoe-site-stage
      trigger: true
    - get: steeltoe-site-1x
      trigger: true
  - task: generate-site-stage
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: steeltoeoss/tools-middleman}
      inputs:
      - name: steeltoe-site-stage
      - name: steeltoe-site-1x
      run: 
        path: bash
        args:
        - "-c"
        - cd steeltoe-site-stage && bundle install && middleman build && cp -R ./build/* ../generated-site-content && cd ../steeltoe-site-1x && middleman build && cp -R ./build/1x ../generated-site-content/1x
      outputs:
      - name: generated-site-content
  - task: create-tarball
    config:
      platform: linux
      image_resource:
          type: docker-image
          source: {repository: steeltoeoss/tools-middleman}
      inputs:
      - name: generated-site-content
      run:
        path: tar
        args:
        - czf
        - steeltoe-tarball/steeltoe-stage-content.tgz
        - generated-site-content
      outputs:
      - name: steeltoe-tarball
  - put: steeltoe-stage-content
    params: {file: steeltoe-tarball/steeltoe-stage-content.tgz}


- name: deploy-staging
  serial: true
  plan:
  - get: steeltoe-site-stage
    passed: [generate-stage-site]
  - get: steeltoe-stage-content
    passed: [generate-stage-site]
  - task: extract-tarball
    config:
      platform: linux
      image_resource:
          type: docker-image
          source: {repository: steeltoeoss/tools-middleman}
      inputs:
      - name: steeltoe-stage-content
      run:
        path: tar
        args:
        - xzf
        - steeltoe-stage-content/test-steeltoe-stage-content.tgz
        - -C
        - extracted-tarball
      outputs:
      - name: extracted-tarball
  - put: deploy-stage
    params:
      manifest: steeltoe-site-stage/manifest-concourse-stage.yml
      path: extracted-tarball/generated-site-content
      current_app_name: steeltoe-test-staging

#### Production Jobs
- name: generate-prod-site
  serial: true
  plan:
  - aggregate:
    - get: steeltoe-site-prod
      trigger: true
    - get: steeltoe-site-1x
      trigger: true
  - task: generate-site
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: steeltoeoss/tools-middleman}
      inputs:
      - name: steeltoe-site-prod
      - name: steeltoe-site-1x
      run: 
        path: bash
        args:
        - "-c"
        - cd steeltoe-site-prod && bundle install && middleman build && cp -R ./build/* ../generated-site-content && cd ../steeltoe-site-1x && middleman build && cp -R ./build/1x ../generated-site-content/1x
      outputs:
      - name: generated-site-content
  - task: create-tarball
    config:
      platform: linux
      image_resource:
          type: docker-image
          source: {repository: steeltoeoss/tools-middleman}
      inputs:
      - name: generated-site-content
      run:
        path: tar
        args:
        - czf
        - steeltoe-tarball/steeltoe-prod-content.tgz
        - generated-site-content
      outputs:
      - name: steeltoe-tarball
  - put: steeltoe-prod-content
    params: {file: steeltoe-tarball/steeltoe-prod-content.tgz}

- name: deploy-prod
  serial: true
  plan:
  - get: steeltoe-site-prod
    passed: [generate-prod-site]
  - get: steeltoe-prod-content
    passed: [generate-prod-site]
  - task: extract-tarball
    config:
      platform: linux
      image_resource:
          type: docker-image
          source: {repository: steeltoeoss/tools-middleman}
      inputs:
      - name: steeltoe-prod-content
      run:
        path: tar
        args:
        - xzf
        - steeltoe-prod-content/test-steeltoe-prod-content.tgz
        - -C
        - extracted-tarball
      outputs:
      - name: extracted-tarball
  - put: deploy-prod
    params:
      manifest: steeltoe-site-prod/manifest-concourse-stage.yml
      path: extracted-tarball/generated-site-content
      current_app_name: steeltoe-test-prod


#### Resources for jobs
resources:
### Github resources
- name: steeltoe-site-prod
  type: git
  source:
    uri: https://github.com/SteeltoeOSS/steeltoe-site.git
    branch: master
    username: {{github_username}}
    password: {{github_password}}

- name: steeltoe-site-1x
  type: git
  source:
    uri: https://github.com/SteeltoeOSS/steeltoe-site.git
    branch: 1.x
    username: {{github_username}}
    password: {{github_password}}

- name: steeltoe-site-stage
  type: git
  source:
    uri: https://github.com/SteeltoeOSS/steeltoe-site.git
    branch: dev
    username: {{github_username}}
    password: {{github_password}}

### Publish to PWS resources
- name: deploy-stage
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: {{cf_username}}
    password: {{cf_password}}
    organization: steeltoe.io
    space: steeltoe.io
    skip_cert_check: false

- name: deploy-prod
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: {{cf_username}}
    password: {{cf_password}}
    organization: steeltoe.io
    space: steeltoe.io
    skip_cert_check: false

### Storage of site contents on S3
- name: steeltoe-stage-content
  type: s3
  source:
    access_key_id: {{access_key_id}}
    secret_access_key: {{secret_access_key}}
    bucket: steeltoe-site-content
    versioned_file: steeltoe-site/test-steeltoe-stage-content.tgz
    region_name: us-west-1

- name: steeltoe-prod-content
  type: s3
  source:
    access_key_id: {{access_key_id}}
    secret_access_key: {{secret_access_key}}
    bucket: steeltoe-site-content
    versioned_file: steeltoe-site/test-steeltoe-prod-content.tgz
    region_name: us-west-1

