---
jobs:
- name: generate-stage-site
  serial: true
  plan:
  - get: steeltoe-site
    trigger: true
  - task: generate-site
    config:
      platform: linux
      image: docker:///steeltoeoss/tools
      inputs:
      - name: steeltoe-site
      run:
        path: /hugo
        args:
        - --source=steeltoe-site
        - --theme=github-project-landing-page
        - --destination=../generated-site-content
      outputs:
      - name: generated-site-content
  - task: create-tarball
    config:
      platform: linux
      image: docker:///steeltoeoss/tools
      inputs:
      - name: generated-site-content
      run:
        path: tar
        args:
        - czf
        - steeltoe-tarball/steeltoe-stage-content.tgz
        - generated-site-content
      outputs:
      - name: steeltoe-tarball
  - put: steeltoe-stage-content
    params: {file: steeltoe-tarball/steeltoe-stage-content.tgz}

- name: deploy-staging
  serial: true
  plan:
  - get: steeltoe-site
    passed: [generate-stage-site]
  - get: steeltoe-stage-content
    trigger: true
    passed: [generate-stage-site]
  - task: extract-tarball
    config:
      platform: linux
      image: docker:///steeltoeoss/tools
      inputs:
      - name: steeltoe-stage-content
      run:
        path: tar
        args:
        - xzf
        - steeltoe-stage-content/steeltoe-stage-content.tgz
        - -C
        - extracted-tarball
      outputs:
      - name: extracted-tarball
  - put: pws-staging
    params:
      manifest: steeltoe-site/manifest-stage.yml
      path: extracted-tarball/generated-site-content
      current_app_name: steeltoe-stage
  - put: slack-alert
    params:
      username: concourse
      icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
      text: <!channel> New Content Deployed to http://steeltoe-stage.cfapps.io by Build $BUILD_ID!

- name: generate-prod-site
  serial: true
  plan:
  - get: steeltoe-site
  - task: generate-site
    config:
      platform: linux
      image: docker:///steeltoeoss/tools
      inputs:
      - name: steeltoe-site
      run:
        path: /hugo
        args:
        - --baseURL=http://steeltoe.io
        - --source=steeltoe-site
        - --theme=github-project-landing-page
        - --destination=../generated-site-content
      outputs:
      - name: generated-site-content
  - task: create-tarball
    config:
      platform: linux
      image: docker:///steeltoeoss/tools
      inputs:
      - name: generated-site-content
      run:
        path: tar
        args:
        - czf
        - steeltoe-tarball/steeltoe-prod-content.tgz
        - generated-site-content
      outputs:
      - name: steeltoe-tarball
  - put: steeltoe-prod-content
    params: {file: steeltoe-tarball/steeltoe-prod-content.tgz}

- name: deploy-prod
  serial: true
  plan:
  - get: steeltoe-site
    passed: [generate-prod-site]
  - get: steeltoe-prod-content
    trigger: true
    passed: [generate-prod-site]
  - task: extract-tarball
    config:
      platform: linux
      image: docker:///steeltoeoss/tools
      inputs:
      - name: steeltoe-prod-content
      run:
        path: tar
        args:
        - xzf
        - steeltoe-prod-content/steeltoe-prod-content.tgz
        - -C
        - extracted-tarball
      outputs:
      - name: extracted-tarball
  - put: pws-prod
    params:
      manifest: steeltoe-site/manifest-prod.yml
      path: extracted-tarball/generated-site-content
      current_app_name: steeltoe-prod

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: steeltoe-site
  type: git
  source:
    uri: git@github.com:SteelToeOSS/steeltoe-site.git
    branch: master
    private_key: {{github_private_key}}

- name: steeltoe-stage-content
  type: s3
  source:
    access_key_id: {{access_key_id}}
    secret_access_key: {{secret_access_key}}
    bucket: steeltoe-site-content
    versioned_file: steeltoe-stage-content.tgz

- name: steeltoe-prod-content
  type: s3
  source:
    access_key_id: {{access_key_id}}
    secret_access_key: {{secret_access_key}}
    bucket: steeltoe-site-content
    versioned_file: steeltoe-prod-content.tgz

- name: pws-staging
  type: cf
  source:
    api: https://api.run.pivotal.io
    username:  mstine+steeltoe-pws@pivotal.io
    password: {{pws_password}}
    organization: spring.io
    space: steeltoe-staging
    skip_cert_check: false

- name: pws-prod
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: mstine+steeltoe-pws@pivotal.io
    password: {{pws_password}}
    organization: spring.io
    space: steeltoe-production
    skip_cert_check: false

- name: slack-alert
  type: slack-notification
  source:
    url: https://hooks.slack.com/services/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
